apiVersion: batch/v1
kind: Job
metadata:
  name: rhbk-ldap-mappers
  namespace: rhbk-gitops
  annotations:
    # Run after realm import
    argocd.argoproj.io/sync-wave: "20"
    # Recreate/re-run on each sync until it succeeds, then remove the Job pod.
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation,HookSucceeded
spec:
  backoffLimit: 6
  # Keep failed pods for debugging; clean up manually after success.
  template:
    metadata:
      labels:
        app.kubernetes.io/name: rhbk-ldap-mappers
    spec:
      restartPolicy: OnFailure
      containers:
        - name: configure
          # Use same image digest as the running Keycloak pods to avoid tag drift
          image: registry.redhat.io/rhbk/keycloak-rhel9@sha256:d339ecf788d1681ba9945a2ea63ca675caec863ec75f497ef916103f4c898003
          imagePullPolicy: IfNotPresent
          env:
            - name: KEYCLOAK_ADMIN
              valueFrom:
                secretKeyRef:
                  name: rhbk-initial-admin
                  key: username
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rhbk-initial-admin
                  key: password
          command: ["/bin/bash", "-ec"]
          args:
            - |
              set -euo pipefail

              KC_URL="http://rhbk-service.rhbk-gitops.svc:8080"
              REALM="rhbk"
              CFG="/tmp/kcadm.config"
              KCADM="/opt/keycloak/bin/kcadm.sh"

              echo "Logging in with kcadm and waiting for LDAP provider to exist..."
              LOGGED_IN="false"
              LAST_ERR=""
              LDAP_ID=""
              # 600*2s = 20 minutes
              for i in $(seq 1 600); do
                if ${KCADM} config credentials --config "${CFG}" --server "${KC_URL}" --realm master \
                  --user "${KEYCLOAK_ADMIN}" --password "${KEYCLOAK_ADMIN_PASSWORD}" >/dev/null 2>/tmp/kcadm.err; then
                  LOGGED_IN="true"

                  # Ensure realm exists before looking for components
                  if ${KCADM} get "realms/${REALM}" --config "${CFG}" --fields realm >/dev/null 2>/tmp/kcadm.err; then
                    COMP_JSON="$(${KCADM} get components -r "${REALM}" --config "${CFG}" \
                      --query "name=openldap" --fields id,providerId 2>/tmp/kcadm.err | tr -d '\r' || true)"
                    LDAP_ID="$(printf '%s' "${COMP_JSON}" | sed -n 's/.*"id"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | head -n 1 || true)"
                    if [ -n "${LDAP_ID}" ]; then
                      break
                    fi
                  fi
                fi

                if [ -s /tmp/kcadm.err ]; then
                  LAST_ERR="$(tail -n 1 /tmp/kcadm.err || true)"
                fi
                sleep 2
              done

              if [ -z "${LDAP_ID}" ]; then
                if [ "${LOGGED_IN}" != "true" ]; then
                  echo "ERROR: failed to login with kcadm to ${KC_URL} (last error: ${LAST_ERR})"
                else
                  echo "ERROR: LDAP provider component 'openldap' not found in realm ${REALM} after waiting (last error: ${LAST_ERR})"
                  echo "Hint: check KeycloakRealmImport status and that component name is 'openldap'."
                  echo "Last provider query output was:"
                  echo "${COMP_JSON:-<empty>}"
                fi
                exit 1
              fi

              echo "LDAP_ID=${LDAP_ID}"

              mapper_exists() {
                local name="$1"
                local json
                json="$(${KCADM} get components -r "${REALM}" --config "${CFG}" \
                  --query "parent=${LDAP_ID}" --query "name=${name}" --fields id 2>/dev/null | tr -d '\r' || true)"
                printf '%s' "${json}" | sed -n 's/.*"id"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | head -n 1 || true
              }

              ensure_mapper_json() {
                local name="$1"; shift
                local providerId="$1"; shift
                local json="$1"; shift

                local existing
                existing="$(mapper_exists "${name}")"
                if [ -n "${existing}" ]; then
                  echo "Mapper '${name}' already exists (${existing})"
                  return 0
                fi

                echo "Creating mapper '${name}'..."
                echo "${json}" | ${KCADM} create components -r "${REALM}" --config "${CFG}" -f -
              }

              # Attribute mappers (required for username)
              ensure_mapper_json "username" "user-attribute-ldap-mapper" \
                "{\"name\":\"username\",\"providerId\":\"user-attribute-ldap-mapper\",\"providerType\":\"org.keycloak.storage.ldap.mappers.LDAPStorageMapper\",\"parentId\":\"${LDAP_ID}\",\"config\":{\"user.model.attribute\":[\"username\"],\"ldap.attribute\":[\"cn\"],\"is.mandatory.in.ldap\":[\"true\"],\"read.only\":[\"true\"],\"always.read.value.from.ldap\":[\"true\"]}}"

              ensure_mapper_json "first name" "user-attribute-ldap-mapper" \
                "{\"name\":\"first name\",\"providerId\":\"user-attribute-ldap-mapper\",\"providerType\":\"org.keycloak.storage.ldap.mappers.LDAPStorageMapper\",\"parentId\":\"${LDAP_ID}\",\"config\":{\"user.model.attribute\":[\"firstName\"],\"ldap.attribute\":[\"givenName\"],\"read.only\":[\"true\"],\"always.read.value.from.ldap\":[\"true\"]}}"

              ensure_mapper_json "last name" "user-attribute-ldap-mapper" \
                "{\"name\":\"last name\",\"providerId\":\"user-attribute-ldap-mapper\",\"providerType\":\"org.keycloak.storage.ldap.mappers.LDAPStorageMapper\",\"parentId\":\"${LDAP_ID}\",\"config\":{\"user.model.attribute\":[\"lastName\"],\"ldap.attribute\":[\"sn\"],\"read.only\":[\"true\"],\"always.read.value.from.ldap\":[\"true\"]}}"

              ensure_mapper_json "email" "user-attribute-ldap-mapper" \
                "{\"name\":\"email\",\"providerId\":\"user-attribute-ldap-mapper\",\"providerType\":\"org.keycloak.storage.ldap.mappers.LDAPStorageMapper\",\"parentId\":\"${LDAP_ID}\",\"config\":{\"user.model.attribute\":[\"email\"],\"ldap.attribute\":[\"mail\"],\"read.only\":[\"true\"],\"always.read.value.from.ldap\":[\"true\"]}}"

              # Group mapper (groupOfNames in ou=Groups)
              ensure_mapper_json "groups" "group-ldap-mapper" \
                "{\"name\":\"groups\",\"providerId\":\"group-ldap-mapper\",\"providerType\":\"org.keycloak.storage.ldap.mappers.LDAPStorageMapper\",\"parentId\":\"${LDAP_ID}\",\"config\":{\"groups.dn\":[\"ou=Groups,dc=example,dc=org\"],\"group.name.ldap.attribute\":[\"cn\"],\"membership.ldap.attribute\":[\"member\"],\"membership.attribute.type\":[\"DN\"],\"user.roles.retrieve.strategy\":[\"LOAD_GROUPS_BY_MEMBER_ATTRIBUTE\"],\"preserve.group.inheritance\":[\"true\"],\"ignore.missing.groups\":[\"true\"],\"drop.non.existing.groups.during.sync\":[\"false\"]}}"

              echo "Done."
