apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: rhbk
  namespace: rhbk-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  instances: 1

  db:
    vendor: postgres
    host: postgresql
    port: 5432
    database: keycloak
    usernameSecret:
      name: postgresql
      key: username
    passwordSecret:
      name: postgresql
      key: password

  http:
    httpEnabled: true

  # OpenShift Route is edge-terminated, so Keycloak must trust forwarded headers
  # and use the correct proxy mode to build absolute URLs for the Admin UI.
  proxy:
    headers: xforwarded

  additionalOptions:
    # NOTE: `proxy` is deprecated in Keycloak 24 but still supported.
    # We set it explicitly to match OpenShift edge termination.
    - name: proxy
      value: edge

  hostname:
    hostname: rhbk-rhbk-gitops.apps.cluster-zrdcz.dynamic.redhatworkshops.io
    strict: false
    strictBackchannel: false

  ingress:
    enabled: true
