apiVersion: v1
kind: Secret
metadata:
  name: openldap
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
type: Opaque
stringData:
  ldapRoot: dc=example,dc=org
  adminUsername: admin
  adminPassword: change-me
  # Bind user recommended for applications (Keycloak/RHBK)
  bindUser: keycloak
  bindPassword: change-me
---
apiVersion: v1
kind: Service
metadata:
  name: openldap
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  labels:
    app.kubernetes.io/name: openldap
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: openldap
  ports:
    - name: ldap
      port: 1389
      targetPort: ldap
    - name: ldaps
      port: 1636
      targetPort: ldaps
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: openldap
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/name: openldap
spec:
  replicas: 1
  serviceName: openldap
  selector:
    matchLabels:
      app.kubernetes.io/name: openldap
  template:
    metadata:
      labels:
        app.kubernetes.io/name: openldap
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: openldap
          image: bitnami/openldap:2.6.8-debian-12-r9
          imagePullPolicy: IfNotPresent
          ports:
            - name: ldap
              containerPort: 1389
            - name: ldaps
              containerPort: 1636
          env:
            - name: LDAP_ROOT
              valueFrom:
                secretKeyRef:
                  name: openldap
                  key: ldapRoot
            - name: LDAP_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: openldap
                  key: adminUsername
            - name: LDAP_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: openldap
                  key: adminPassword
            - name: LDAP_USERS
              valueFrom:
                secretKeyRef:
                  name: openldap
                  key: bindUser
            - name: LDAP_PASSWORDS
              valueFrom:
                secretKeyRef:
                  name: openldap
                  key: bindPassword
            - name: LDAP_ALLOW_ANON_BINDING
              value: "no"
          volumeMounts:
            - name: data
              mountPath: /bitnami/openldap
          readinessProbe:
            tcpSocket:
              port: ldap
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 12
          livenessProbe:
            tcpSocket:
              port: ldap
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 6
          resources:
            requests:
              cpu: 50m
              memory: 256Mi
            limits:
              cpu: "1"
              memory: 1Gi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
