apiVersion: v1
kind: ConfigMap
metadata:
  name: openldap-seed-ldif
  annotations:
    argocd.argoproj.io/sync-wave: "5"
data:
  seed.ldif: |
    dn: ou=Users,dc=example,dc=org
    objectClass: top
    objectClass: organizationalUnit
    ou: Users

    dn: ou=Groups,dc=example,dc=org
    objectClass: top
    objectClass: organizationalUnit
    ou: Groups

    dn: cn=ldaptest,ou=Users,dc=example,dc=org
    objectClass: top
    objectClass: person
    objectClass: organizationalPerson
    objectClass: inetOrgPerson
    cn: ldaptest
    sn: test
    givenName: LDAP
    mail: ldaptest@example.org
    userPassword: test123

    dn: cn=rhbk-testers,ou=Groups,dc=example,dc=org
    objectClass: top
    objectClass: groupOfNames
    cn: rhbk-testers
    description: Test group for RHBK LDAP mapper validation
    member: cn=ldaptest,ou=Users,dc=example,dc=org
---
apiVersion: batch/v1
kind: Job
metadata:
  name: openldap-seed
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  backoffLimit: 6
  template:
    metadata:
      labels:
        app.kubernetes.io/name: openldap-seed
    spec:
      restartPolicy: OnFailure
      containers:
        - name: seed
          image: osixia/openldap:1.5.0
          imagePullPolicy: IfNotPresent
          env:
            - name: LDAP_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: openldap
                  key: adminPassword
          command: ["/bin/bash", "-ec"]
          args:
            - |
              LDAP_URL="ldap://openldap.rhbk-gitops.svc:389"
              BASE_DN="dc=example,dc=org"
              ADMIN_DN="cn=admin,${BASE_DN}"

              echo "Waiting for LDAP to be reachable..."
              for i in $(seq 1 60); do
                if ldapsearch -x -H "${LDAP_URL}" -D "${ADMIN_DN}" -w "${LDAP_ADMIN_PASSWORD}" -b "${BASE_DN}" -s base "(objectClass=*)" dn >/dev/null 2>&1; then
                  break
                fi
                sleep 2
              done

              echo "Seeding user/group via LDIF (idempotent)..."
              # -c continues on errors like 'Already exists'
              ldapadd -c -x -H "${LDAP_URL}" -D "${ADMIN_DN}" -w "${LDAP_ADMIN_PASSWORD}" -f /seed/seed.ldif || true

              echo "Verifying user and group exist..."
              ldapsearch -x -H "${LDAP_URL}" -D "${ADMIN_DN}" -w "${LDAP_ADMIN_PASSWORD}" -b "${BASE_DN}" "(cn=ldaptest)" dn
              ldapsearch -x -H "${LDAP_URL}" -D "${ADMIN_DN}" -w "${LDAP_ADMIN_PASSWORD}" -b "${BASE_DN}" "(cn=rhbk-testers)" dn
          volumeMounts:
            - name: seed
              mountPath: /seed
      volumes:
        - name: seed
          configMap:
            name: openldap-seed-ldif
